// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nmrdmrifljueujqbjugh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5tcmRtcmlmbGp1ZXVqcWJqdWdoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc1NDIzNDksImV4cCI6MjA3MzExODM0OX0.kz0ULw36uD2gVkFklnwdANeULWbwEjfdwaLL5cvOD2s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});